from app.providers.base import AIProvider
from app.schemas.request import GenerationRequest


class MockProvider(AIProvider):
    name = "mock"

    async def generate(
        self,
        request: GenerationRequest,
        model: str,
    ) -> str:
        return (
            "Response generated by MockProvider. "
            "Fallback executed successfully."
        )